services:
  h_front_db:
    image: ${PGSQL_VERSION}
    restart: always
    container_name: ${PROJECT_NAME}_db
    tty: true
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    ports:
      - "5542:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    networks:
      - h_back_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  h_front_adminer:
    image: ${ADMINER_VERSION}
    container_name: ${PROJECT_NAME}_adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
    networks:
      - h_back_net

networks:
  h_back_net:
    driver: bridge
